name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.302'

    - name: Restore dependencies
      run: dotnet restore ./IluminaçõesPublica/SistemaIluminacaoPublica.csproj

    - name: Build
      run: dotnet build ./IluminaçõesPublica/SistemaIluminacaoPublica.csproj --configuration Release

    - name: Test
      run: dotnet test ./IluminaçõesPublica/SistemaIluminacaoPublica.csproj --configuration Release
